#!/usr/bin/env python3
import csv
import sys
import matplotlib.pyplot as plt

def read_csv(path):
    hit_idx = []
    hit_dist = []
    drop_points = []

    with open(path, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            hit_idx.append(int(row["hit_index"]))
            hit_dist.append(int(row["hit_distance"]))
            drop_points.append(int(row["drop_point"]))

    return hit_idx, hit_dist, drop_points


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 plot_jackpot_distribution.py jackpot_stats.csv")
        sys.exit(1)

    csv_path = sys.argv[1]
    hit_idx, hit_dist, drop_points = read_csv(csv_path)

    # ---------------------------
    # 1. Scatter plot (distribution of distances)
    # ---------------------------
    plt.figure(figsize=(12, 6))
    plt.scatter(hit_idx, hit_dist, s=10, c="blue", alpha=0.6)
    plt.title("Jackpot Hit Distances (iterations until hit)")
    plt.xlabel("Hit index")
    plt.ylabel("Hit distance (iterations)")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig("v1/stats/jackpot_distribution_scatter.png", dpi=150)
    print("Saved: v1/stats/jackpot_distribution_scatter.png")

    # ---------------------------
    # 2. Histogram (probability distribution)
    # ---------------------------
    plt.figure(figsize=(12, 6))
    plt.hist(hit_dist, bins=40, color="green", alpha=0.7)
    plt.title("Distribution of Jackpot Hit Distances")
    plt.xlabel("Hit distance (iterations)")
    plt.ylabel("Frequency")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig("v1/stats/jackpot_distribution_histogram.png", dpi=150)
    print("Saved: v1/stats/jackpot_distribution_histogram.png")

    # ---------------------------
    # 3. Drop Point plot
    # ---------------------------
    plt.figure(figsize=(12, 6))
    plt.plot(hit_idx, drop_points, marker="o", markersize=3, linestyle="-", color="red")
    plt.title("Drop Points per Jackpot Reset")
    plt.xlabel("Hit index")
    plt.ylabel("Drop point (generated by engine)")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig("v1/stats/jackpot_drop_points.png", dpi=150)
    print("Saved: v1/stats/jackpot_drop_points.png")

    # ---------------------------
    # 4. Normalized ratio hit_distance / drop_point
    # ---------------------------
    ratios = [hit_dist[i] / drop_points[i] for i in range(len(hit_dist))]

    plt.figure(figsize=(12, 6))
    plt.plot(hit_idx, ratios, marker=".", linestyle="none", color="purple", alpha=0.6)
    plt.title("Hit Distance Ratio = hit_distance / drop_point")
    plt.xlabel("Hit index")
    plt.ylabel("Ratio")
    plt.grid(True)
    plt.tight_layout()
    plt.savefig("v1/stats/jackpot_hit_ratio.png", dpi=150)
    print("Saved: v1/stats/jackpot_hit_ratio.png")

    print("\nAll graphs saved!")


if __name__ == "__main__":
    main()